# Introduction

Hello, and welcome to Rise and Fall. Episode 5. Gamal Abdel Nasser.

Last time, we started off our Washington Post sub-series by covering the prime-ministership of Margaret Thatcher between 1979 and 1990. Today, we will be shifting our attention to North Africa and continue our sub-series by analyzing the rise and fall of Gamal Abdel Nasser in Egypt between the 1950's and 1970.

Up to now, we've always considered the articles that relate to the leaders entrance into and exit out of office. However, this kind of analysis has two drawbacks. The first is that newspapers may be covering these leaders in more than two articles; not considering other articles into account can severely limit how news coverage evolved over time, which is what we're interested in.

The second problem is about defining entrance and exit itself. Basically, the rising to and the fall from power is much easier to identify in, say, countries with regular fair and free elections, than in dictatorships.

Nasser is a good example of how messy the rise to power is in a dictatorship. Nowadays, it looks that he became leader of Egypt in July 1952, after masterminding a coup that overthrew King Farouk. However, the truth is that Mohamed Naguib, a general and war hero in the army, was the most senior leader of the coup and he, not Nasser, became President of the newly acclaimed republic and kept some real power for a while. Only in 1956, after a long low-intensity power struggle with Naguib, Nasser became the _President_ of Egypt.

So, when can we consider Nasser as becoming Egypt's leader? And, equally importantly, when did the Washington Post consider it? We selected three articles. The first is from 1953, and gives a profile of all the key players involved in the military coup, and subsequent administration of Egypt. This article gives the most insight about Nasser himself and his political stance. The second article is a short article written in 1955, on the heels of the purges following an assassination attempt on Nasser. The article is a short op-ed that admits Nasser was the mastermind behind the revolution all along. The third article, written in 1956, reports that Nasser has become the president of Egypt. While the third article would normally be our rise article, we chose the first article to be our main rise article.

As can be seen, Nasser's rise to power was a fantastically intricate and, perhaps, worthy of his spectacular career. He was born the son of a postal clerk in 1918 and joined political activism during high school when many Egyptians protested and actively opposed the British presence in Egypt. He was a non-elite Arab in a country headed by a King who took pride of his Albanian origins while British officials controlled the defense, foreign affairs, and the Suez canal. Nasser thus felt naturally inclined towards the emerging left-wing Arab nationalism, and he quickly recognized that the military was, historically, the perfect place to change the country.

From 1937, he served as an officer in the Egyptian army while remaining politically active. His career included active duty in the the 1948 Arab-Israeli war whose humiliating outcome convinced many young officers, including Nasser, that Egypt’s politics had to change dramatically. As we discussed before, that change came in 1952 and, after a complicated sequence of events, Nasser became president of Egypt in 1956.

Soon, Nasser nationalized the Suez Canal under the pretext of financing the Aswan dam. His determination when facing the invasion by the UK, France and Israel signals that he understood that the European colonial empires could not act without American support and against Soviet power. His charisma help captivating the support of all Egyptians and Arabs, despite the horrific military losses. His success allowed him to become the great leader of the Arab world and the great inspiration of Arab nationalism, even after Egypt’s crushing defeat against Israel in the Six-Day War in 1967. Indeed, when he died in 1970, Egypt was officially called United Arab Republic, a residue of the failed attempt in uniting with Syria. All of his personal ventures allowed him to simultaneously gain support from Soviet Union and respect from the US.

Despite Nasser’s achievements, his critics will point at the military autocracy founded by Nasser, a state of affairs that continues today.

Like in other episodes, we will judge the coverage of the rise and of the fall, not the legacy of the politician!

# Part 1: Technical Analysis

And so, we start off with the technical analysis. We will be looking at the evolution of coverage in a technical perspective with the four articles we have - Rise of 1953 (the main rise article), Rise of 1955, Rise of 1956 and Fall.

It should first be established that these articles differ somewhat from each other in terms of the purpose they were written for. Rise of 1953 and Rise of 1955 are profiling articles. They look at Nasser and discuss about his general disposition and status in Egypt's politics. Rise of 1956 and Fall, on the other hand, are event articles: respectively, they report on Nasser becoming the president of Egypt, and on his death. Hence, the profiling articles are generally longer than the event articles. Rise of 1953 and Rise of 1955 have 1517 and 291 words, respectively. Rise of 1956 and Fall have 404 and 882 words, respectively. 

This fluctuation in word count - starting very high, then dipping and then becoming relatively high again - reflect the Washington Post's sentiments towards Nasser. In Rise of 1953 and Rise of 1955, the NLTK sentiment analysis estimates positive sentiments to be doubly present, relative to the negative sentiments. These are the years 1952 and 1953, where Nasser is seen as a modernizer that wants to establish a respectable, anti-communist and republican Egypt. It's only in Rise of 1956, the article on him becoming President, is it clear that he is also a Machiavellian political operator who has won an election without any competition. The negative sentiment in Rise of 1956 is triple that of the positive sentiment. 

Given this state of affairs, one would expect a cheerful article to mark Nasser's death. However, we see the exact opposite - the Fall article has a negative sentiment score almost equal to its positive one. Perhaps this is due to his death being premature and unexpected, and literally hours after securing peace between Arafat and the Jordanian crown in a summit in Cairo.

# Part 2: Themes and Contents

This evolution of sentiments around the coverage of Nasser - enthusiasm, disillusionment and shell shock - coincide well with the themes and contents in these articles. Furthermore, Nasser’s achievements seemed to made the coverage to focus on his most salient skill: a charismatic dealmaker. In the interest of time, we'll only look at the themes and contents in Rise of 1953 and Fall articles.

The Rise of 1953 dedicates 62% of its words to the profiles of the 12 conspirators of the 1952 coup. Although Nasser was not the leader of the coup, his profile already takes 21% of the words of that article. Other topics, like the developments surrounding the Suez canal, do not take more than 15% of the words. And even those subjects are typically used to illustrate the profile of the conspirators. For example, the article quotes Nasser stating that “Life is limited. One can die in the Suez Canal Zone as well as anywhere else if fate wants it so.”

Interestingly, the article explores the rumors that Nasser may be trying to remove Naguib: 52% of the words dedicated to describe Nasser’s profile go to signs and incidents of a potential low-level power struggle. For instance, the article includes the following passage: “Rumors, not borne out by facts, have been circulated that Nasser is the "Gray eminence" behind Naguib - the man who pulls the strings and who will eventually take over power.“

Inevitably, the fall article dedicates 31% of its words to cover Nasser’s unexpected death - he was only 52 years old - such as the announcement in the radio and vice-president Sadat’s tears. The death and funeral preparations have the longest passages, on average, of all themes shows that those were the main themes of the article.

Nasser’s charisma is the second most important topic, taking 23% of the article’s words and having 6 passages, as many as his death and funeral. Furthermore, there is a chance that the number of words dedicated to his death and funeral is a by-product of Nasser’s charisma. See the following example: “He had been one of the most beloved leader in the Arab world, and people wept in capital throughout the Middle East. Official mourning was declared throughout Egypt for 40 days.”

And even the remaining themes of the article seemed to be affected by his charisma. When talking about his importance for the politics of the Arab world, the article states that “It was under Nasser’s influence that Jordan’s King Hussein and Arab guerrilla chief Yasser Arafat had signed a peace agreement only yesterday in Cairo to end the civil strife that had torn Jordan asunder.” When the article turns to the potential successor’s of Nasser, it mentions that “In Washington, sources said Sadat is perfectly capable of administering the country and running the army but has no charisma.”

It is true that the fall article mentions topics that are important because of Nasser’s material impact in different domains. First, Nasser not only had an impact on Egypt but also on geopolitics when he provided motivation for a generation of Arab leaders and managed to get political and material support from both sides of the Cold War while never committing himself to either. Second, his succession was a complicated affair since, as the article makes clear, Sadat did not seem to be more than a good administrator and there were no credible candidates from other political circles. However, Nasser’s main tool, his charisma, seemed to have affected the Washington Post’s coverage as much as it affected Egypt and the world during his lifetime.

# Part 3: Interesting Nuggets

There are some interesting nuggets to point out across the two key articles, Rise of 1953 and Fall. 

The first nugget comes exclusively from the Rise of 1953. At the very end of the article, after having praised the dedication of the revolutionary officers, a note is made about the officers being new to politics. Even at that point, it was very clear that these officers were skillful politicians. Indeed, what was less clear is how skillful they were in military affairs. Additionally, the article underscores their honesty and faith, two ironic words given the crackdown on the Muslim Brotherhood and the tight control of the Egyptian economy by the military since that 1952 coup.

The second nugget comes from both Rise of 1953 and Fall articles. In Rise of 1953, General Amer is profiled as the head of the army. In the Fall article, General Amer is again mentioned as the head of the army. It is interesting to see a familiar name in a familiar position across two points in time where this can't be said of many others. That may also be a sign of the slow consolidation of political institutions under Nasser.

The final nugget comes exclusively from the Fall article. While reflecting on Nasser's rise to become the leader of Egypt, it is reported that he took power "easily" away from Naguib after the 1952 coup. The reality is much more muddy - Nasser faced a lot of serious competition between 1952 and 1956, and his accession was the result of skill and luck. However, this nugget shows just how powerful the myth of Nasser had become by the 1970's - even for this refutable Western newspaper.

# Conclusion

And that's it - we've come to the end of the episode. Nasser, a leader who shaped Egypt into the country we know today. He was a smart, charismatic and ambitious leader who transformed Egypt. However, the continuity of coups and military men leading the country also points to the shortcomings of that transformation. Thank you very much for tuning in!

Please share your views, suggestions for future episodes and everything else that comes to mind on our Facebook page “Rise and Fall”.

If you prefer, you can send an email to rise.and.fall.press@gmail.com. We only ask you to make your comments and suggestions constructively.

See you all next time!
