---
title: "Luiz Inacio Lula de Silva"
author: "Guilherme Oliveira and Mehmet Kutluay"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Hello, and welcome to Rise and Fall. Episode 3. Luiz Inacio Lula de Silva.

Last time, we analyzed articles from The Economist that covered the presidency of Nicolas Sarkozy between 2007 and 2012. Today, we will be shifting our attention to the Americas and look at how El Pais covered Luiz Inacio Lula de Silva's first and last day in office - the 1st of January 2003 and 31st of December 2010. For simplicity, and to stop committing felonies to any Portuguese-speaking ears, I will refer to him as Lula from here on.

Coming from Turkey, I am naturally disposed to be more than ignorant about politicians and leaders from countries outside of the U.S., Europe and the Middle East. However, Lula was a name that I'd heard of before. I'd be willing to bet that many other people might say the same thing - that he is the first Brazilian president they'd heard of, during his term. Ten years after his departure from the presidency, the popularity of his mandates appears to have been matched by the controversy over his legacy. 

Lula came from a working class background and was able to secure the presidency in his fourth attempt. When he won, Lula became the first openly leftist president since 1964. This year was then a coup took place in Brazil that initiated a military dictatorship.  

For Lula's supporters, his presidency was the starting point for a new Brazil, in which the expansion of social programs like Bolsa Família and Fome Zero were done. It was through these programs that he kept his election promise: to ensure that Brazilians had three meals a day. Furthermore these promises were kept while Lula kept the economy on a growth path. In fact, Brazil went through the 2007-2008 financial crisis in relatively good health. Unlike fellow socialists like Chavista's in Venezuela and Kirchnerista's in Argentina, he kept good relations with the IMF and used public-private partnerships to sustain the economy.

He managed to have Brazil become a more geopolitically important player. For instance, he mediated talks on the Iranian nuclear crisis. Brazil became a member of the G20 and is touted as a candidate for one of the permanent seats in the UN Security Council - if this body is ever updated. 

His critis though, see these events differently. For them, Lula's presidency represents the starting point of the degradation of Brazilian political life. He was almost illiterate by the time he became president and was the first to come from a working class background. Moreover, many of the social policies that he took credit for were already in place by the time he came to power. And the success with the economy? As many other developing countries, Brazil benefitted from the commodity boom before the 2007-2007 financial crisis. In fact, Lula left unresolved financial problems to his successor - pension financing being the more infamous one of them.

Hindsight is always 20/20. These criticism are easy to make due to the events that followed Lula's presidency. His successor, Dilma Rouseff, got impeached in 2016. The following year, Lula himself was sentenced to nine and a half years in jail for money laundering and corruption. This was one of the more famous convictions to come out of the Operation Lava Jato investigations. Despite all of this, he still tried to run for the 2018 presidential election - but was barred from doing so. This last turn of events potentially allowed the current Brazilian president to win a landslide victory.  

In other words, Lula's story and character evoke such passion that our perception of his time in office is easily distorted. Therefore, Guilherme and I would like to refresh our collective memory of two snippets of news from when Lula was in power. 

The reasons for choosing Lula are clear, but what about for choosing El Pais? We chose this newspaper for four reasons. One, we wanted to do something different to the first two episodes, and do our analysis through a non-English medium. Second, El Pais is a major international newspaper that is known to extensively cover Latin America. Third, El Pais offers a fair amount of access to it's articles for free. And last, it is a traditionally center-of-left newspaper - a fitting medium for the background on Lula we just discussed. On this last point, El Pais is also slightly controversial. In 2016, it was revealed that El Pais' Brazilian subsidiary had received funds from Lula's Worker's Party.

Needless to say, we expect extremely positive coverage of Lula in both the article on the rise and the article on the fall of Lula.

The rise article is from October 22nn, 2002, two days after the second round of the Brazilian presidential elections. The fall article is from October 31st, 2010, on the day of the second round of the Brazilian presidential elections, before the results were known. Lula was unable to run in this election due to constitutional limits on presidential terms.

Though we suspect the rise and fall articles from El Pais to be very favorable to Lula, there is still an eight year gap between them. Those eight years are quite dense - not only for what Lula did as president, but also how Brazilian democracy had the chance to mature. A lot may have changed, which is precisely what we look for in this podcast: the nature and evolution of press coverage.

As ever, we make no attempt to make a fair judgement of Lula's life and work. We seek to compare and constrast the coverage of Lula's rise and fall. We compare and contrast across three categories: technical aspects, contents/themes and interesting nuggets.

# Part 1: Technical Analysis

And so, we start off with the technical aspects. We focus on the differences before the similarities. 

The first difference that we can see is that the author is declared for the rise article, while this is not the case for the fall article. There is also a difference in length. The rise article, with it's 704 word count, is significantly shorter than the fall article, which has 945 words. This difference in length can also be felt when one reads the articles. The fall article makes use of much longer sentences - to the point where one paragraph can consist of one sentence. The sentences themselves largely consist of indirect speech. The rise article, on the other hand, has shorter sentences, with more usage of direct speech. This is more in line with what one might expect from a typical article in a newspaper.

One other difference is the way the articles choose to present their stories. The rise article starts by describing a speech given by Lula, and then dives into policy, geopolitics and election promises. All of this is decorated with quotes from Lula's speech. The fall article, on the other hand, does not build itself around an event. It is a commentary on Lula's time in office, who is being set up to succeed him and Brazil's future. Very much in the style of a wizened political commentator telling you their opinion over a cup of tea.

That bring us to the most important difference. The rise article is indeed from the print edition of El Pais - in fact it was one of the cover articles for the day it was published. So it's objective is to report an event that has happened. The fall article, on the other hand, was never published in the print edition. It's from the webpage of El Pais - which makes it more likely to be an editorial, where events are commented on.

This explains the differences we have seen - in terms of length, writing style and, as we've touched upon briefly for the time being, content. 

We've talked about the technical differences - what about the similarities? When the articles are about a left-wing president from a left-wing newspaper, one would expect that the overall sentiment is positive. That is more or less what we see across both articles. From a qualitative perspective, this is clear at first read. Lula is the charismatic political leader. He might be a populist and rough around the edges, but he has promised policies in the rise article that have been largely delivered according to the fall article.

From a quantitative perspective, things are not so clear cut. This is largely due to the fact that the articles are originally written in Spanish. Algorithms and machine learning algorithms that are widely available for predicting sentiment in texts are largely optimized for English. However we were able to find one repository on GitHub that contains a sentiment predictor model trained on Spanish online retail reviews. We thank the owner of the sentiment-analysis-spanish package for open sourcing this piece of code, as we have used it for this episode.

We do the sentiment analysis in two levels - sentence and paragraph. What does this mean exactly? Let's take the example of doing it at the paragraph level. We predict the sentiment score for each paragraph in an article, and then calculate the average across all paragraphs, to get an idea for the whole article. We do the same for sentences. We do this because the model we are using is trained on texts that are not as long as news articles, so we need to provide it with input that is similar, at least in length, to what it has been trained on. 

At the sentence level, the results are 0.086 for the rise article and 0.087 for the fall article. At the paragraph level, the results are 0.27 for both articles. Keep in mind that the scores can be at minimum 0, indicating the most negative sentiment, and at maximum 1, indicating the most positive sentiment. So analyzing paragraph by paragraph paints a happier picture.

But what does this mean really? The scores by themselves should not mean too much, because the model that is generating them is trained on retail reviews - not news articles. This is equivalent to how you might evalute the review of Italian cuisine by a food taster who specializes in Japanese food. Do they know a thing or two about food? Yes! But would you trust their evaluation of carbonara or of sashimi? Of course the sashimi. It's a similar story with the individual sentiment scores we get.

But should we completely ignore this food taster when in Rome? Well, maybe there is some value to be had in terms of how they compare dishes to each other, rather than a judgement on one dish by itself. They might like the carbonara of restaurant A over restaurant B, and give them different scores. So we might go to restaurant A instead of B. 

Looked at this way, the sentiment scores we get per level are essentially equal to each other. So we can say that the sentiment in both articles are not largely different. Going back to our carbonara example - it doesn't matter which restaurant you go to. Both serve the same quality carbonara - whether this is good or bad carbonara is a different matter.

We test this claim, that the articles have similar sentiments, by running the translated versions of the articles through the NLTK package that we've been using in previous episodes. The claim largely holds up. The output is that 5.2% of the rise article has negative sentiments, while this is 4.7% for the fall article. In terms of positive sentiments, it is 15.1% of the rise article while 12.8% of the fall article.

If anyone fits this analysis into the carbonara metaphor I tortured you with, and writes it in the comments, we will send you a cookie.

# Part 2: Themes and Contents

We carry onto the second part of our episode - themes and contents of the articles. In this case, we see many more stark contrasts than similarities between the two articles. Yes, both articles express general positivity towards Lula, however they are different about where they focus this positivity on. 

In order to help us better deep dive into these differences and similarities, Guilherme generously counted the number of words and sentences in each article that are allocated to Lula's message, economic issues, social issues, geopolitics and Brazilian internal politics. The relative percentage of words and sentences in the rise article for each topic are quite similar to each other. For instance 23% of all words are dedicated to describing economic issues. The percentage of sentences that are dedicated to this is 22%. A fun side fact - this reflects how most sentences in the rise article have similar lenghts to each other.

As I said before, in terms of content, the two articles are quite different. The rise article is an introduction to Lula's term in office - where policies are discussed in between quotes of Lula's speech. In this article, Lula the person and his message is front and center. In the fall article, this changes. Lula's time in office and his achievements/failures are barely mentioned. Instead, the focus is on what awaits Brazil going forward - and not only with the heir apparentto Lula - Dilma Rousseff - but with the overall political scene. 

Those that are looking for hints of foreshadowing, as we saw in the Sarkozy articles, will be disappointed. No mention is made of a right-wing populist backlash, or of the potential popularity of a little-known eccentric congressman named Jair Bolsonaro. Instead two presidential candidates of the 2010 presidential election are discussed as being potential frontrunners in a future election. These candidates are Marino Silva of the Green Party and Aecio Neves of the center-left PSDB. There is even talk of Marino Silva potentially being able to rule via a left-wing coalition of Lula's Workers Party and his PSDB. The future is predicted as very conciliatory, environmentally-friendly and left wing. An interesting contrast to where Brazil is today in 2020.

We can see this change in terms of content by looking at the share of words used for economic and social issues between the two articles. In the rise article, 23% of all words are dedicated to economic issues, and 14% of all words are dedicated to social issues. In the fall article, these numbers drop to 12% and 4% respectively. This kind of decrease is even more pronounced when we look at the proportion of words dedicated to Lula's message. In the rise article this is a whopping 62% of words. In the fall article, this number is 23%. As statements on legacy are also considered to be a part of this category, this is interesting. The fall article does not give too much space to the direct legacy of Lula. For a left-wing newspaper reporting on a very popular left-wing president, this is noteworthy.

Let's take a minute to digest what this means in the context of Lula himself. One of the most positive things someone can say about Lula is the fact that he lifted millions out of poverty through his social programmes while also honoring Brazil's debts - something only the rise article touches upon as an ambition. Like him or hate him, he actually managed to deliver on his promise of improving the economy and the lives of the poort at the same time. Thus it is surprising that the fall article would not accentuate these points much when compared to the rise article. Perhaps these accomplishments had already been touted many times before by El Pais, and it was time to start talking about the future.

This brings us to the next major difference between the two articles. The rise article makes practically no mention at all of the internal politics of Brazil. Lula's rivals in the presidential election are not mentioned for instance. In the fall article, however, a full 48% of words are dedicated to the internal politics of Brazil and what the future has in store for the country's political landscape. And the passages dedicated to this topic are the exceptionally long ones. Because while 48% of all the words in the fall article are dedicated to internal politics, these words are squeezed into 31% of the passages. So these sentences are, on average, have 1.5 times more words than other sentences in the fall article. 

Although the articles are different content-wise, they are similar in how much relative room they give to geopolitics. 11% of words and passages in the rise article are dedicated to geopolitics - specifically Lula's potential relationship with the United States. The fall article allocates less words to geopolitics - 6% - but a similar amount of passages - 12%. This tells us that these sentences are the relatively shorter ones. 

Another similarity is, as stated before, that both articles are generally positive about Lula. The fall article is slightly more constrained in this manner than the rise article. Even the few mentions of Lula's authoritarian or populist tendencies are brushed over quite quickly. The rise article, on the other hand, acknowledges some worries about Lula but then is quick to point out that these may be alarmist


# Part 3: Interesting Nuggets

Finally, we move on to the last section: the interesting nuggets. We start with the curiosities related to the rest of the world.

The rise article briefly refers to the George W. Bush administration's intention to create a free trade zone for the Americas. It is funny how the Republican Party lost its appetite for international trade agreements but maintained its belief in American exceptionalism: the rise article also mentions Lula's promise to cooperate with the international community, in a clear allusion to the American refusal to ratify the Kyoto Protocol and to join the International Criminal Court. On the other hand, the fall article never mentions the 2007-2008 financial crisis, which Lula apparently managed well, nor comments on the end of the commodity boom, which helped so much in the Brazilian economic expansion in the first decade of the 21st century.

Turning to domestic politics, the rise article begins with Lula's calls to national unity and social cohesion. However, Lula did not miss the opportunity to honor his leftist comrades: “We carry his legacy and his passion for justice [...] My heart is pounding. I feel like a new Brazil is being born.”. Also in the same article, as one of the measures to encourage cohesion in Brazil, Lula announces the creation of the ‘Council for Social and Economic Development’. However, for those familiar with Latin American politics, this smacks of one of those bodies to buy political favors than to effectively resolve something. The fall article does not mention the output of this council.

Speaking of which, in the fall article there is speculation about the hypothesis of Dilma Rousseff simply acting as a placeholder to Lula. In other words, she would run her mandate and then Lula would return in the 2014 election to carry out two more mandates without having to change the constitution. Two years before the fall article came out, Dmitry Medvedev had become the president of Russia to precisely do this. Two years later, Putin was back as president and by 2020 he had changed the constitution to stay in power for much longer. Had Brazilian politics turned out differently - maybe without the Lava Jato investigation becoming so all-encompassing - would Lula have done the same as Putin? Maybe yes, maybe no. It's still some nice alternative history to chew on.

We come to our next nugget. The fall article states the following about Lula:

“The vast majority of Brazilians forgave him for everything, such as the megalomania in which he came to compare himself with Jesus Christ or when he boasted that he had never read a book. They forgave him for all his bravado, his daily metamorphoses, those moments when he was able to defend in the afternoon what he had attacked in the morning.”

Looking at the impeachment of Dilma Rousseff in 2016, the 2018 presidential election and the current political environment in Brazil, this pardon seems to not have lasted long.

To end this section, I will tell you one last nugget that does not appear in any of the news. His name, in public memory and in this episode, may be Lula. However he was not born with this name. It was only in 1982 that Lula da Silva included his nickname “Lula” in his official name.

# Conclusion

And that's it - we've come to the end of the episode. Lula, a man whose political legacy continues to be profound in one of the world's most diverse and large countries. Thank you very much for tuning in!

Please share your views, suggestions for future episodes and everything else that comes to mind on our Facebook page “Rise and Fall”.

If you prefer, you can send an email to rise.and.fall.press@gmail.com. We only ask you to make your comments and suggestions constructively.

See you all next time!